include(ExternalProject)

set(LIBP2P_SOURCE_DIRECTORY "${CMAKE_SOURCE_DIR}/../dependencies/libp2p")
set(LIBP2P_BUILD_DIRECTORY "${CMAKE_SOURCE_DIR}/../dependencies/libp2p-${CMAKE_SYSTEM_PROCESSOR}-${CMAKE_SYSTEM_NAME}")
set(LIBP2P_VERSION "0.5")

file(MAKE_DIRECTORY ${LIBP2P_BUILD_DIRECTORY})

ExternalProject_Add(libp2p
  GIT_REPOSITORY https://github.com/eXtremal-ik7/libp2p
  GIT_TAG master
  GIT_SHALLOW 1
  SOURCE_DIR ${LIBP2P_SOURCE_DIRECTORY}
  SOURCE_SUBDIR "src"
  BINARY_DIR ${LIBP2P_BUILD_DIRECTORY}
  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  INSTALL_COMMAND ""
  UPDATE_COMMAND ""
)

if (MSVC)
  add_library(ASYNCIO_LIBRARY_DEBUG            STATIC IMPORTED DEPENDS libp2p)
  add_library(ASYNCIO_LIBRARY_OPTIMIZED        STATIC IMPORTED DEPENDS libp2p)
  add_library(ASYNCIO_EXTRAS_LIBRARY_DEBUG     STATIC IMPORTED DEPENDS libp2p)
  add_library(ASYNCIO_EXTRAS_LIBRARY_OPTIMIZED STATIC IMPORTED DEPENDS libp2p)
  add_library(P2P_LIBRARY_DEBUG                STATIC IMPORTED DEPENDS libp2p)
  add_library(P2P_LIBRARY_OPTIMIZED            STATIC IMPORTED DEPENDS libp2p)
  add_library(P2PUTILS_LIBRARY_DEBUG           STATIC IMPORTED DEPENDS libp2p)
  add_library(P2PUTILS_LIBRARY_OPTIMIZED       STATIC IMPORTED DEPENDS libp2p)

  set_target_properties(ASYNCIO_LIBRARY_DEBUG            PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/asyncio/Debug/asyncio-${LIBP2P_VERSION}d.lib)
  set_target_properties(ASYNCIO_LIBRARY_OPTIMIZED        PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/asyncio/Release/asyncio-${LIBP2P_VERSION}.lib)
  set_target_properties(ASYNCIO_EXTRAS_LIBRARY_DEBUG     PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/asyncioextras/Debug/asyncioextras-${LIBP2P_VERSION}d.lib)
  set_target_properties(ASYNCIO_EXTRAS_LIBRARY_OPTIMIZED PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/asyncioextras/Release/asyncioextras-${LIBP2P_VERSION}.lib)
  set_target_properties(P2P_LIBRARY_DEBUG                PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/p2p/Debug/p2pd.lib)
  set_target_properties(P2P_LIBRARY_OPTIMIZED            PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/p2p/Release/p2p.lib)
  set_target_properties(P2PUTILS_LIBRARY_DEBUG           PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/p2putils/Debug/p2putilsd.lib)
  set_target_properties(P2PUTILS_LIBRARY_OPTIMIZED       PROPERTIES IMPORTED_LOCATION ${LIBP2P_BUILD_DIRECTORY}/p2putils/Release/p2putils.lib)

  set(ASYNCIO_LIBRARY        debug ASYNCIO_LIBRARY_DEBUG        optimized ASYNCIO_LIBRARY_OPTIMIZED)
  set(ASYNCIO_EXTRAS_LIBRARY debug ASYNCIO_EXTRAS_LIBRARY_DEBUG optimized ASYNCIO_EXTRAS_LIBRARY_OPTIMIZED)
  set(P2P_LIBRARY            debug P2P_LIBRARY_DEBUG            optimized P2P_LIBRARY_OPTIMIZED)
  set(P2PUTILS_LIBRARY       debug P2PUTILS_LIBRARY_DEBUG       optimized P2PUTILS_LIBRARY_OPTIMIZED)
else()
    add_library(ASYNCIO_LIBRARY__        STATIC IMPORTED DEPENDS libp2p)
    add_library(ASYNCIO_EXTRAS_LIBRARY__ STATIC IMPORTED DEPENDS libp2p)
    add_library(P2P_LIBRARY__            STATIC IMPORTED DEPENDS libp2p)
    add_library(P2PUTILS_LIBRARY__       STATIC IMPORTED DEPENDS libp2p)

    set_target_properties(ASYNCIO_LIBRARY__ PROPERTIES
      IMPORTED_LOCATION_DEBUG ${LIBP2P_BUILD_DIRECTORY}/asyncio/${CMAKE_STATIC_LIBRARY_PREFIX}asyncio-${LIBP2P_VERSION}d${CMAKE_STATIC_LIBRARY_SUFFIX}
      IMPORTED_LOCATION_RELEASE ${LIBP2P_BUILD_DIRECTORY}/asyncio/${CMAKE_STATIC_LIBRARY_PREFIX}asyncio-${LIBP2P_VERSION}${CMAKE_STATIC_LIBRARY_SUFFIX}
    )

    set_target_properties(ASYNCIO_EXTRAS_LIBRARY__ PROPERTIES
      IMPORTED_LOCATION_DEBUG ${LIBP2P_BUILD_DIRECTORY}/asyncioextras/${CMAKE_STATIC_LIBRARY_PREFIX}asyncioextras-${LIBP2P_VERSION}d${CMAKE_STATIC_LIBRARY_SUFFIX}
      IMPORTED_LOCATION_RELEASE ${LIBP2P_BUILD_DIRECTORY}/asyncioextras/${CMAKE_STATIC_LIBRARY_PREFIX}asyncioextras-${LIBP2P_VERSION}${CMAKE_STATIC_LIBRARY_SUFFIX}
    )

    set_target_properties(P2P_LIBRARY__ PROPERTIES
      IMPORTED_LOCATION_DEBUG ${LIBP2P_BUILD_DIRECTORY}/p2p/${CMAKE_STATIC_LIBRARY_PREFIX}p2pd${CMAKE_STATIC_LIBRARY_SUFFIX}
      IMPORTED_LOCATION_RELEASE ${LIBP2P_BUILD_DIRECTORY}/p2p/${CMAKE_STATIC_LIBRARY_PREFIX}p2p${CMAKE_STATIC_LIBRARY_SUFFIX}
    )

    set_target_properties(P2PUTILS_LIBRARY__ PROPERTIES
      IMPORTED_LOCATION_DEBUG ${LIBP2P_BUILD_DIRECTORY}/p2putils/${CMAKE_STATIC_LIBRARY_PREFIX}p2putilsd${CMAKE_STATIC_LIBRARY_SUFFIX}
      IMPORTED_LOCATION_RELEASE ${LIBP2P_BUILD_DIRECTORY}/p2putils/${CMAKE_STATIC_LIBRARY_PREFIX}p2putils${CMAKE_STATIC_LIBRARY_SUFFIX}
    )

    set(ASYNCIO_LIBRARY        ASYNCIO_LIBRARY__)
    set(ASYNCIO_EXTRAS_LIBRARY ASYNCIO_EXTRAS_LIBRARY__)
    set(P2P_LIBRARY            P2P_LIBRARY__)
    set(P2PUTILS_LIBRARY       P2PUTILS_LIBRARY__)
endif()

set(ASYNCIO_INCLUDE_DIR
  ${LIBP2P_SOURCE_DIRECTORY}/src/include
  ${LIBP2P_BUILD_DIRECTORY}/include
)
